// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HashingServiceInterface is an autogenerated mock type for the HashingServiceInterface type
type HashingServiceInterface struct {
	mock.Mock
}

// CompareHashPassword provides a mock function with given fields: password, hashedPassword
func (_m *HashingServiceInterface) CompareHashPassword(password string, hashedPassword string) (bool, error) {
	ret := _m.Called(password, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(password, hashedPassword)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hashedPassword)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(password, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashPassword provides a mock function with given fields: password
func (_m *HashingServiceInterface) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHashingServiceInterface creates a new instance of HashingServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashingServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashingServiceInterface {
	mock := &HashingServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
