// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	models "github.com/R-Thibault/OrgaJobSearch/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// ApplicationServiceInterface is an autogenerated mock type for the ApplicationServiceInterface type
type ApplicationServiceInterface struct {
	mock.Mock
}

// SaveApplication provides a mock function with given fields: userID, appData
func (_m *ApplicationServiceInterface) SaveApplication(userID uint, appData models.Application) error {
	ret := _m.Called(userID, appData)

	if len(ret) == 0 {
		panic("no return value specified for SaveApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.Application) error); ok {
		r0 = rf(userID, appData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApplicationServiceInterface creates a new instance of ApplicationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationServiceInterface {
	mock := &ApplicationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
