// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	models "github.com/R-Thibault/OrgaJobSearch/backend/models"
	mock "github.com/stretchr/testify/mock"
)

// RoleRepositoryInterface is an autogenerated mock type for the RoleRepositoryInterface type
type RoleRepositoryInterface struct {
	mock.Mock
}

// GetRoleByName provides a mock function with given fields: roleName
func (_m *RoleRepositoryInterface) GetRoleByName(roleName string) (*models.Role, error) {
	ret := _m.Called(roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByName")
	}

	var r0 *models.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Role, error)); ok {
		return rf(roleName)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Role); ok {
		r0 = rf(roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoleRepositoryInterface creates a new instance of RoleRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepositoryInterface {
	mock := &RoleRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
