// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// JWTTokenGeneratorServiceInterface is an autogenerated mock type for the JWTTokenGeneratorServiceInterface type
type JWTTokenGeneratorServiceInterface struct {
	mock.Mock
}

// GenerateJWTToken provides a mock function with given fields: tokenType, email, expirationTime
func (_m *JWTTokenGeneratorServiceInterface) GenerateJWTToken(tokenType *string, email string, expirationTime time.Time) (string, error) {
	ret := _m.Called(tokenType, email, expirationTime)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWTToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, string, time.Time) (string, error)); ok {
		return rf(tokenType, email, expirationTime)
	}
	if rf, ok := ret.Get(0).(func(*string, string, time.Time) string); ok {
		r0 = rf(tokenType, email, expirationTime)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*string, string, time.Time) error); ok {
		r1 = rf(tokenType, email, expirationTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTTokenGeneratorServiceInterface creates a new instance of JWTTokenGeneratorServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTTokenGeneratorServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTTokenGeneratorServiceInterface {
	mock := &JWTTokenGeneratorServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
