// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// JWTTokenGeneratorUtilInterface is an autogenerated mock type for the JWTTokenGeneratorUtilInterface type
type JWTTokenGeneratorUtilInterface struct {
	mock.Mock
}

// GenerateJWTToken provides a mock function with given fields: tokenType, body, expirationTime
func (_m *JWTTokenGeneratorUtilInterface) GenerateJWTToken(tokenType string, body string, expirationTime time.Time) (string, error) {
	ret := _m.Called(tokenType, body, expirationTime)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWTToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, time.Time) (string, error)); ok {
		return rf(tokenType, body, expirationTime)
	}
	if rf, ok := ret.Get(0).(func(string, string, time.Time) string); ok {
		r0 = rf(tokenType, body, expirationTime)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, time.Time) error); ok {
		r1 = rf(tokenType, body, expirationTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTTokenGeneratorUtilInterface creates a new instance of JWTTokenGeneratorUtilInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTTokenGeneratorUtilInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTTokenGeneratorUtilInterface {
	mock := &JWTTokenGeneratorUtilInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
